SELECT
    item.ID_COMPRA, compra.DT_COMPRA as DT_COMPRA, item.ID_ITEM, item.CODIGOBR, item.UNIDADE,
    item.REGISTRO_ANVISA, item.CNPJ_FORNECEDOR, item.CNPJ_FABRICANTE,
    item.QT_ITEM_COMPRA AS QT_UNIDADES,
    item.VL_ITEM_COMPRA AS VL_UNITARIO, (item.QT_ITEM_COMPRA * item.VL_ITEM_COMPRA) AS VL_TOTAL_ITEM,  
    PJFabricante.RAZAO_SOCIAL AS FABRICANTE,
    PJFornecedor.RAZAO_SOCIAL AS FORNECEDOR
FROM
    item
LEFT JOIN
    (SELECT CNPJ, RAZAO_SOCIAL FROM PJ) AS PJFabricante
ON
    item.CNPJ_FABRICANTE = PJFabricante.CNPJ
LEFT JOIN
    (SELECT CNPJ, RAZAO_SOCIAL FROM PJ) AS PJFornecedor
ON
    item.CNPJ_FORNECEDOR = PJFornecedor.CNPJ
LEFT JOIN
    (SELECT ID_COMPRA, DT_COMPRA FROM compra) AS compra
ON
    item.ID_COMPRA = compra.ID_COMPRA
